title: Cesar Orozco
logo: /assets/img/logo.png
description: Software developer & Data Engineer
show_downloads: false
show_social: true
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: true
  owner_url: https://github.com/cesarorozcom
  owner_name: cesarorozcom
  repository_url: https://github.com/cesarorozcom/cesarorozcom.github.io