title: Cesar Orozco
logo: /assets/img/logo.png
bold:
  - business value
description: "
  <br>
  Experienced Data Engineer Adept at understanding client data needs and stakeholder requirements, utilizing data and software engineering techniques to create <b>business value</b> through data accessibility. 
  Proficiency in identifying, acquiring, cleansing, and storing data, while developing reusable <b>data products</b> aligned with defined architecture patterns.
  Proven ability to work effectively with <b>cross-disciplinary collaborators and partners</b> across multiple business entities.
"

show_downloads: false
show_social: true
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
  owner_url: https://github.com/cesarorozcom
  owner_name: cesarorozcom
  repository_url: https://github.com/cesarorozcom/cesarorozcom.github.io