title: Cesar Orozco
logo: /assets/img/logo.png
bold:
  - business value
description:

show_downloads: false
show_social: true
google_analytics: G-3RVPBZDHWM
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: true
  owner_url: https://github.com/cesarorozcom
  owner_name: cesarorozcom
  repository_url: https://github.com/cesarorozcom/cesarorozcom.github.io